// Common first names used to gate the StoreLeads-personal fallback.
// Without this, single-word locals like custom@, consumercare@, gcc@ pass
// as "real first name" because they're 2-12 lowercase letters not in the
// shared-mailbox blacklist. We only accept locals that match a known name.
//
// List is intentionally short (~600 entries) — the most common
// English/European first names. If a real name is missing the lead is
// skipped (better than emailing a shared inbox addressed "Hi Custom,").
//
// Refresh by appending names; lookup is a Set so additions are O(1).

const FIRST_NAMES = [
  // Top English (US/UK)
  "aaron","abby","abbey","abigail","adam","adrian","aidan","alan","albert","alex","alexander","alexandra","alexis","alfie","alfred","alice","alicia","alison","allison","amanda","amber","amelia","amy","ana","anastasia","andrea","andrew","andy","angela","angelica","angelo","anita","ann","anna","anne","annette","annie","anthony","antonio","april","archer","archie","ariana","arthur","ashley","ashton","aubrey","audrey","austin","ava","avery","ayla","azura",
  "bailey","barbara","barry","beatrice","becky","belinda","ben","benjamin","bennett","bernard","beth","bethany","betty","beverly","bianca","bill","billie","billy","blake","bob","bobby","bonnie","brad","bradley","brandon","brandy","brendan","brenda","brent","brett","brian","briana","brianna","bridget","brittany","brody","brooke","brooks","bruce","bryan","bryce","byron",
  "caitlin","caleb","callie","calvin","cameron","camila","camille","candace","cara","carey","carl","carla","carlos","carmen","carol","caroline","carolyn","carrie","carson","carter","casey","cassandra","cassidy","catherine","cathy","cecil","cecilia","cedric","celeste","celia","chad","charlene","charles","charlie","charlotte","chase","chelsea","cheryl","chester","chris","christian","christina","christine","christopher","cindy","claire","clara","clarence","claudia","clay","clayton","cliff","clifford","clinton","clyde","cody","colby","cole","colin","colleen","collin","conner","connor","conrad","corey","cory","courtney","craig","crystal","curtis","cynthia",
  "dale","dallas","damian","damon","dan","dana","dane","daniel","danielle","danny","daphne","darcy","daria","darren","daryl","dave","david","dawn","dean","deanna","deborah","debra","declan","delaney","delia","della","delphine","denise","dennis","derek","derrick","desiree","destiny","devin","dexter","diana","diane","dick","diego","dion","dolly","dominic","don","donald","donna","donovan","dora","doreen","doris","dorothy","doug","douglas","drew","duane","duncan","dustin","dwayne","dwight","dylan",
  "eamon","earl","ed","eddie","edgar","edith","edmund","edna","edward","edwin","eileen","eleanor","elena","elias","eli","elijah","elise","eliza","elizabeth","ella","ellen","ellie","elliot","ellis","elsie","elton","elvis","emerson","emery","emily","emma","emmanuel","emmett","eric","erica","erika","erin","ernest","ernie","esmeralda","estelle","esther","ethan","eugene","eva","evan","evangeline","evelyn","everett","ezra",
  "faith","felicia","felix","fernando","finn","finnegan","fiona","flora","florence","floyd","forrest","frances","francesca","francis","francisco","frank","franklin","fred","freddie","frederick","freya",
  "gabe","gabriel","gabriella","gail","gareth","garrett","gary","gavin","gemma","gene","geoff","geoffrey","george","georgia","georgina","gerald","gerard","gerry","gianna","gilbert","gillian","gina","ginger","giovanna","giovanni","glen","glenda","glenn","gloria","gordon","grace","graham","grant","greg","gregory","greta","griffin","gus","guy","gwen","gwyneth",
  "hailey","hal","hank","hannah","harlan","harley","harold","harriet","harrison","harry","harvey","hayden","hayley","hazel","heath","heather","hector","heidi","helen","helena","henry","herbert","herman","hilary","hillary","holly","homer","hope","howard","hugh","hugo","hunter","hutch",
  "ian","imogen","ines","ingrid","irene","iris","irving","isaac","isabel","isabella","isabelle","isaiah","ivan","ivy",
  "jace","jack","jackie","jackson","jacob","jacqueline","jada","jade","jake","jamal","james","jamie","jan","jane","janelle","janet","janice","janine","jared","jarrod","jarvis","jasmine","jason","jasper","javier","jay","jayden","jean","jeanette","jeanne","jeff","jefferson","jeffrey","jen","jenna","jenni","jennie","jennifer","jenny","jeremy","jerome","jerry","jess","jesse","jessica","jessie","jett","jill","jim","jimmy","jo","joan","joanna","joanne","jocelyn","jodi","jody","joe","joel","john","johnny","jolene","jon","jonah","jonathan","jordan","jorge","jose","josefina","joseph","josephine","josh","joshua","josiah","joy","joyce","juan","judith","judy","julia","julian","juliana","julianne","julie","juliet","june","justin","justine",
  "kara","karen","kari","karl","karla","kasey","kate","katelyn","katherine","kathleen","kathryn","kathy","katie","katy","kayla","kaylee","keegan","keira","keith","kelly","kelsey","ken","kendall","kendra","kennedy","kenneth","kenny","kent","kerri","kerry","kevin","khloe","kiana","kim","kimberly","kira","kirk","kirsten","kit","klaus","kris","krista","kristen","kristin","kristina","kristine","kristopher","kurt","kyla","kyle","kylie","kyra",
  "lacey","lana","lance","landon","lara","larry","laura","laurel","lauren","laurence","laurie","lawrence","layla","leah","lee","leila","len","lena","leo","leon","leona","leonard","leonardo","leroy","leslie","lester","levi","lewis","liam","lila","lilia","lilian","liliana","lillian","lilly","lily","lin","linda","lindsay","lindsey","lionel","lisa","liza","lloyd","logan","loic","lois","lola","lon","lonnie","lora","lorenzo","loretta","lori","lorraine","lottie","louie","louis","louise","luca","lucas","lucia","lucy","luigi","luis","luke","lyle","lynda","lynette","lynn",
  "mabel","mac","mack","maddie","maddy","madeline","madison","mae","maggie","makayla","malcolm","mallory","mandy","manuel","marc","marcia","marco","marcus","margaret","margot","maria","marian","marie","marilyn","mario","marion","marisa","marisol","marissa","mark","marlene","marlon","marshall","martha","martin","marty","marvin","mary","mason","mateo","matilda","matt","matteo","matthew","mattie","maureen","maurice","mauricio","max","maximilian","maxine","maxwell","may","maya","megan","meghan","mel","melanie","melinda","melissa","melody","melvin","mercedes","meredith","mia","micah","michael","michele","michelle","mickey","miguel","mike","mikey","miles","milly","milton","mindy","miranda","miriam","misty","mitch","mitchell","mohammad","mohammed","molly","monica","monique","montana","monty","morgan","muriel","murray","myra","myron",
  "nadia","nadine","nancy","naomi","natalia","natalie","natasha","nate","nathan","nathaniel","neil","nell","nelson","nestor","nettie","neva","nia","nic","nicholas","nick","nicole","nicolette","niel","nigel","nikki","nikolas","nina","noah","noel","noelle","nolan","nora","norma","norman",
  "octavia","odette","olive","oliver","olivia","ollie","omar","oren","oscar","otis","owen",
  "pablo","paige","pam","pamela","pat","patricia","patrick","patty","paul","paula","paulina","pauline","payton","pearl","pedro","peggy","penelope","penny","percy","perry","pete","peter","phil","philip","phillip","phoebe","phyllis","pia","pierce","pierre","piper","preston","priscilla",
  "quentin","quincy","quinn",
  "rachel","rachelle","rae","rafael","ralph","ramona","ramsey","randall","randy","raphael","raquel","raul","ray","raymond","reagan","rebecca","reed","reese","reggie","reginald","rene","renee","reuben","rex","rey","rhea","rhonda","ricardo","richard","rick","rickey","ricky","riley","rita","rob","robbie","robert","roberta","roberto","robin","robyn","rocco","rod","roderick","rodger","rodney","rodolfo","rodrigo","roger","rolando","roman","ronald","ronnie","rory","rosa","rosalind","rosalinda","rose","rosemarie","rosemary","ross","roxanne","roy","ruben","ruby","rudolph","rudy","russell","rusty","ruth","ryan","ryder",
  "sabine","sabrina","sadie","sage","sally","sam","samantha","samir","samuel","sandra","sandy","sara","sarah","sasha","saul","savannah","scarlett","scott","sean","sebastian","selena","selina","serena","sergio","seth","shana","shane","shannon","sharon","shaun","shauna","shawn","shay","sheila","shelby","sheldon","shelley","sherri","sherry","sheryl","sid","sidney","sienna","silas","silvia","simon","simone","sloan","sloane","sofia","sol","solomon","sonia","sonja","sophia","sophie","spencer","stacey","stacy","stan","stanley","stefan","stefania","stella","stephanie","stephen","steve","steven","stevie","stewart","stuart","sue","summer","susan","susanne","susie","sven","sybil","sydney","sylvia",
  "tabitha","tamara","tammy","tania","tanya","tara","tatiana","taylor","ted","teresa","terri","terrence","terri","terry","tessa","thaddeus","thelma","theo","theodore","theresa","thomas","tia","tiffany","tim","timothy","tina","toby","todd","tom","tommy","tony","tori","tracey","tracy","travis","trent","trevor","trey","tricia","trish","tristan","troy","trudy","tucker","ty","tyler","tyrone","tyson",
  "ulysses","uma","ursula",
  "valentina","valentino","valeria","valerie","van","vance","vanessa","veronica","vicki","vicky","victor","victoria","vince","vincent","viola","violet","virgil","virginia","vivian",
  "wade","walker","wallace","walt","walter","wanda","warren","wayne","wendell","wendy","wes","wesley","whitney","willa","william","willie","willow","wilma","winston",
  "xavier","xena",
  "yara","yasmin","yolanda","yusuf","yvette","yvonne",
  "zach","zachary","zack","zane","zara","zelda","zion","zoe","zoey",
];

export const FIRST_NAME_SET = new Set(FIRST_NAMES);
export function isLikelyFirstName(local) {
  if (!local) return false;
  return FIRST_NAME_SET.has(local.toLowerCase());
}
