#!/usr/bin/env node
// Linkable Outreach — StoreLeads → Hunter (→ Apollo fallback) → Lemlist
//
// Targeting (per playbook):
//   - Shopify, $50k–$200k/month revenue, US/UK/CA/AU
//   - Beauty, wellness, supplements, skincare
// Sending:
//   - This script only PUSHES leads to Lemlist.
//   - Lemlist owns the actual send schedule (50/day, Tue–Thu 9am–6pm) via campaign settings.
//   - Lemlist also owns the 3-email sequence (cam_XThggBG9AHG62Bg5e).
//
// Personalization variable wired into the Lemlist template: {{personalizedLine}}
// Generated by Claude using brand name + description + Instagram bio (if present).

import { supabase } from "../lib/supabase.js"; // also loads server/.env

const TEAM_ID = "a0000000-0000-0000-0000-000000000001";

// --- Required env ---
const STORELEADS_KEY = process.env.STORELEADS_KEY;
const HUNTER_API_KEY = process.env.HUNTER_API_KEY;
const APOLLO_API_KEY = process.env.APOLLO_API_KEY;
const LEMLIST_KEY = process.env.LEMLIST_KEY;
const LEMLIST_CAMPAIGN_ID = process.env.LEMLIST_CAMPAIGN_ID;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

const missing = [
  ["STORELEADS_KEY", STORELEADS_KEY],
  ["HUNTER_API_KEY", HUNTER_API_KEY],
  ["APOLLO_API_KEY", APOLLO_API_KEY],
  ["LEMLIST_KEY", LEMLIST_KEY],
  ["LEMLIST_CAMPAIGN_ID", LEMLIST_CAMPAIGN_ID],
].filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  console.error(`Missing required env vars: ${missing.join(", ")}`);
  process.exit(1);
}

const MAX_LEADS = parseInt(process.env.LEMLIST_MAX_LEADS_PER_RUN || "100", 10);
const DEADLINE = new Date(Date.now() + 12 * 3600000);
const DELAY_MS = 8000;

// --- StoreLeads filter (built as JSON, then URL-encoded) ---
// Revenue: er=5,000,000–20,000,000 → $50k–$200k/month (scale ÷100).
// Countries: STORELEADS_COUNTRIES env (default US/UK/CA/AU). Override per run, e.g. STORELEADS_COUNTRIES=GB.
// Categories: beauty, wellness, supplements, skincare (broad — Storeleads taxonomy).
const COUNTRIES = (process.env.STORELEADS_COUNTRIES || "US GB CA AU").trim();
const STORELEADS_FILTER = {
  must: {
    conjuncts: [
      { field: "p", operator: "or", analyzer: "advanced", match: "1" }, // Shopify
      { field: "er", min: 5000000, max: 20000000, inclusive_min: true, inclusive_max: true },
      { field: "cc", operator: "or", analyzer: "advanced", match: COUNTRIES },
      {
        field: "cat", operator: "or", analyzer: "advanced",
        match: [
          "/Beauty...&...Fitness",
          "/Beauty...&...Fitness/Face...&...Body...Care",
          "/Beauty...&...Fitness/Face...&...Body...Care/Skin...&...Nail...Care",
          "/Beauty...&...Fitness/Face...&...Body...Care/Make-Up...&...Cosmetics",
          "/Beauty...&...Fitness/Face...&...Body...Care/Perfumes...&...Fragrances",
          "/Beauty...&...Fitness/Fitness",
          "/Health/Nutrition",
        ].join(" "),
      },
    ],
  },
};
const STORELEADS_BQ = "bq=" + encodeURIComponent(JSON.stringify(STORELEADS_FILTER));

let nextCursor = null;
let pushed = 0;
let skipped = 0;
let failed = 0;

const delay = (ms) => new Promise(r => setTimeout(r, ms));
const pastDeadline = () => new Date() >= DEADLINE;

// --- StoreLeads ---
async function fetchStoreLeadsNext() {
  const url = nextCursor
    ? `https://storeleads.app/json/api/v1/all/domain?${STORELEADS_BQ}&cursor=${encodeURIComponent(nextCursor)}`
    : `https://storeleads.app/json/api/v1/all/domain?${STORELEADS_BQ}`;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await fetch(url, {
        headers: { "Authorization": `Bearer ${STORELEADS_KEY}` },
        signal: AbortSignal.timeout(60000),
      });
      if (!res.ok) throw new Error(`StoreLeads API: ${res.status}`);
      const data = await res.json();
      nextCursor = data.has_next_page ? data.next_cursor : null;
      return { domains: data.domains || [], hasMore: !!data.has_next_page };
    } catch (e) {
      if (attempt < 3) await delay(5000); else throw e;
    }
  }
}

// --- Hunter (primary per playbook) ---
// Only fetches people in executive or marketing departments (kills Finance/Sales/Ops directors at source).
// Then role-scores within that pool: founder/C-suite > marketing leadership > marketing IC.
async function hunterFindDecisionMaker(domain) {
  try {
    const params = new URLSearchParams({
      domain,
      api_key: HUNTER_API_KEY,
      limit: "25",
      department: "executive,marketing",
    });
    const res = await fetch(`https://api.hunter.io/v2/domain-search?${params}`, {
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return null;
    const data = await res.json();

    // Word-boundaries on acronyms — without \b, "cto" matches "director".
    const isFounder = (p) => /\b(founder|co-?founder|ceo|owner|president)\b/.test(p);
    const isCSuite = (p) => /\b(cmo|cto|coo|cfo|chief)\b/.test(p);
    const isMarketingLead = (p) =>
      /\b(head of|vp|vice president|director of)\b.*\b(marketing|growth|brand|partnership|creator|influencer|digital|ecommerce|e-commerce)\b/.test(p) ||
      /\b(marketing|growth|brand|partnership|creator|influencer|digital|ecommerce|e-commerce)\b.*\b(director|head|lead|vp|vice president)\b/.test(p);
    const isMarketingIC = (p) =>
      /\b(marketing|growth|brand|partnership|creator|influencer|digital|ecommerce|e-commerce)\b/.test(p);

    const scored = (data.data?.emails || [])
      .filter(e => e.confidence >= 70 && e.first_name)
      .map(e => {
        const pos = (e.position || "").toLowerCase();
        let score = 0;
        if (isFounder(pos)) score = 10;
        else if (isCSuite(pos)) score = 9;
        else if (isMarketingLead(pos)) score = 8;
        else if (isMarketingIC(pos)) score = 6;
        // anything else (Finance Director, Sales Director, Creative Director, etc.) → 0 → rejected
        return { ...e, roleScore: score };
      })
      .filter(e => e.roleScore >= 6)
      .sort((a, b) => b.roleScore - a.roleScore || b.confidence - a.confidence);

    if (scored.length === 0) return null;
    const best = scored[0];
    return {
      email: best.value,
      firstName: best.first_name,
      lastName: best.last_name || "",
      position: best.position || "",
      linkedinUrl: best.linkedin || "",
      source: "hunter",
      roleScore: best.roleScore,
    };
  } catch { return null; }
}

// --- Apollo (fallback per playbook) ---
async function apolloFindDecisionMaker(domain) {
  try {
    const orgRes = await fetch(`https://api.apollo.io/v1/organizations/enrich?domain=${domain}`, {
      headers: { "X-Api-Key": APOLLO_API_KEY },
      signal: AbortSignal.timeout(10000),
    });
    if (!orgRes.ok) return null;
    const orgData = await orgRes.json();
    const personIds = orgData.organization?.org_chart_root_people_ids || [];

    if (personIds.length > 0) {
      const personRes = await fetch("https://api.apollo.io/v1/people/match", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-Api-Key": APOLLO_API_KEY },
        body: JSON.stringify({ id: personIds[0] }),
        signal: AbortSignal.timeout(10000),
      });
      if (personRes.ok) {
        const personData = await personRes.json();
        const p = personData.person;
        if (p?.email && p.email_status === "verified" && p.first_name) {
          return {
            email: p.email, firstName: p.first_name, lastName: p.last_name || "",
            position: p.title || "", linkedinUrl: p.linkedin_url || "", source: "apollo",
          };
        }
      }
    }
    return null;
  } catch { return null; }
}

// Decode the HTML entities Claude sometimes emits (& → &amp; in brand names like "Wren & Wild").
function decodeHtmlEntities(s) {
  if (!s) return s;
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, " ");
}

// Hunter occasionally returns merged co-founders ("Sarah And-Lauren-Murrell") in firstName.
// Take just the first proper name token; reject if it looks unsalvageable.
function normalizeFirstName(raw) {
  if (!raw) return null;
  let n = raw.trim();
  // If it contains "and"/"&" (joined people), or any space, take the first word.
  if (/\b(and|&)\b/i.test(n) || /\s/.test(n)) {
    n = n.split(/[\s]+/)[0];
  }
  // Compound like "Sarah And-Lauren-Murrell" — split on hyphen too if more than one capital chunk.
  if ((n.match(/-/g) || []).length >= 1 && /[A-Z][a-z]+-[A-Z]/.test(n)) {
    n = n.split("-")[0];
  }
  // Sanity: a real first name is 2–20 chars, only letters/apostrophes.
  if (n.length < 2 || n.length > 20) return null;
  if (!/^[A-Za-zÀ-ÿ'’]+$/.test(n)) return null;
  return n;
}

// --- Claude personalised opening line (playbook step "Personalisation") ---
// Returns null on refusal/sparse-data — caller falls back to safe template.
function isUsableLine(text) {
  if (!text || text.length < 15 || text.length > 250) return false;
  const lower = text.toLowerCase();
  // Refusal / clarification-request patterns Claude emits when context is too thin.
  const REFUSAL = [
    "i don't have", "i do not have", "i cannot", "i can't", "i'm not able", "i am not able",
    "could you share", "could you provide", "please share", "please provide",
    "more details", "more context", "more information",
    "to write", "to generate", "to create a",
    "what they do", "what aspect", "what you'd like",
    "without more", "without additional",
  ];
  if (REFUSAL.some(s => lower.includes(s))) return false;
  // Unrendered placeholders or template literals.
  if (/\[(?:brand|company|name|description|tagline|insert)/i.test(text)) return false;
  if (/\{\{[a-z]+\}\}/i.test(text)) return false;
  return true;
}

async function generatePersonalizedLine({ brandName, description, instagramBio, websiteTagline }) {
  if (!ANTHROPIC_API_KEY) return null;
  // If we have no context at all, don't even ask Claude — go straight to fallback.
  if (!description && !instagramBio && !websiteTagline) return null;
  const prompt = `Write one sentence acknowledging this brand's work in a genuine way.
Brand: ${brandName}
${instagramBio ? `Instagram bio: ${instagramBio}\n` : ""}${websiteTagline ? `Website: ${websiteTagline}\n` : ""}${description ? `Description: ${description}\n` : ""}
Keep it under 20 words, conversational, no flattery. Output the sentence only — no quotes, no preamble. If the context is too thin to write something specific, output the single word: SKIP`;
  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 80,
        messages: [{ role: "user", content: prompt }],
      }),
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) return null;
    const data = await res.json();
    let text = data.content?.[0]?.text?.trim().replace(/^["']|["']$/g, "");
    if (!text || text.toUpperCase() === "SKIP") return null;
    text = decodeHtmlEntities(text);
    return isUsableLine(text) ? text : null;
  } catch { return null; }
}

// --- Lemlist ---
async function addLeadToLemlist(email, variables) {
  try {
    const url = email
      ? `https://api.lemlist.com/api/campaigns/${LEMLIST_CAMPAIGN_ID}/leads/${encodeURIComponent(email)}`
      : `https://api.lemlist.com/api/campaigns/${LEMLIST_CAMPAIGN_ID}/leads`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Authorization": "Basic " + Buffer.from(`:${LEMLIST_KEY}`).toString("base64"),
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ ...variables, deduplicate: true }),
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) {
      const text = await res.text();
      return { success: false, error: `Lemlist ${res.status}: ${text.slice(0, 200)}` };
    }
    const data = await res.json();
    return { success: true, leadId: data._id };
  } catch (e) {
    return { success: false, error: e.message };
  }
}

// --- Dedup ---
async function wasAlreadyContacted(domain) {
  const root = domain.split(".")[0];
  const { data } = await supabase
    .from("email_sends").select("id")
    .eq("team_id", TEAM_ID)
    .in("status", ["sent", "pending"])
    .ilike("to_email", `%${root}%`)
    .limit(1);
  return (data?.length || 0) > 0;
}
async function wasAlreadyInLemlist(email) {
  const { data } = await supabase
    .from("email_sends").select("id")
    .eq("team_id", TEAM_ID).eq("to_email", email).limit(1);
  return (data?.length || 0) > 0;
}

// --- Store brand ---
async function storeBrand(domain, data) {
  const emails = (data.contact_info || []).filter(c => c.type === "email").map(c => c.value);
  await supabase.from("storeleads_brands").upsert({
    domain: domain.replace(/^www\./, ""),
    merchant_name: data.merchant_name || null,
    title: data.title || null,
    description: data.description || null,
    platform: data.platform || null,
    plan: data.plan || null,
    country_code: data.country_code || null,
    currency_code: data.currency_code || null,
    city: data.city || null,
    language_code: data.language_code || null,
    email: null,
    emails,
    contact_info: data.contact_info || [],
    avg_price: data.avg_price_formatted || null,
    created_at_storeleads: data.created_at || null,
    last_updated_at: data.last_updated_at || null,
    trustpilot_rating: data.trustpilot?.avg_rating || null,
    trustpilot_reviews: data.trustpilot?.review_count || null,
    about_us: data.about_us || null,
    contact_page: data.contact_page || null,
    raw_data: data,
    imported_at: new Date().toISOString(),
    emailed: true,
    emailed_at: new Date().toISOString(),
  }, { onConflict: "domain" });
}

// --- Per-brand pipeline ---
async function processBrand(domainData, index) {
  const cleanDomain = (domainData.name || "").replace(/^www\./, "").toLowerCase();
  if (!cleanDomain) return "skip";

  if (await wasAlreadyContacted(cleanDomain)) {
    skipped++;
    console.log(`  SKIP: ${cleanDomain} — already contacted`);
    return "skip";
  }

  const isValidDecisionMakerEmail = (email, firstName, lastName, position) => {
    if (!email || !firstName) return false;
    const local = email.split("@")[0].toLowerCase();
    const emailDomain = email.split("@")[1]?.toLowerCase();
    const brandRoot = cleanDomain.split(".")[0];
    if (!emailDomain || !emailDomain.includes(brandRoot)) return false;
    const GENERIC = ["hello", "info", "contact", "hi", "team", "support", "help", "cs",
      "orders", "returns", "press", "pr", "media", "service", "customerservice",
      "customerservices", "customercare", "care", "admin", "webmaster", "noreply",
      "sales", "wholesale", "billing", "legal", "privacy", "hr", "careers", "jobs",
      "mail", "general", "office", "shop", "store", "ecom", "ecommerce"];
    if (GENERIC.some(g => local === g || local.startsWith(g + "."))) return false;
    const pos = (position || "").toLowerCase();
    // Acronyms get \b boundaries — without them, "cto" matches "director" (di-reCTOr).
    const isDecisionMaker = /\b(founder|co-?founder|ceo|coo|cmo|cto|cfo|owner|president|chief)\b|marketing|growth|\bbrand\b|\bcreator\b|influencer|partnership|ecommerce|e-commerce|digital/.test(pos);
    if (!isDecisionMaker) return false;
    const fn = firstName.toLowerCase();
    const ln = (lastName || "").toLowerCase();
    return local.includes(fn) || (ln && local.includes(ln)) ||
      /^[a-z]{2,15}[._][a-z]{2,15}$/.test(local);
  };

  // Playbook order: Hunter first, Apollo as fallback. Skip if both fail.
  let contact = null;
  const hunter = await hunterFindDecisionMaker(cleanDomain);
  if (hunter && isValidDecisionMakerEmail(hunter.email, hunter.firstName, hunter.lastName, hunter.position)) {
    contact = hunter;
  }
  if (!contact) {
    const apollo = await apolloFindDecisionMaker(cleanDomain);
    if (apollo && isValidDecisionMakerEmail(apollo.email, apollo.firstName, apollo.lastName, apollo.position)) {
      contact = apollo;
    }
  }
  if (!contact) {
    skipped++;
    console.log(`  SKIP: ${cleanDomain} — no valid decision maker via Hunter or Apollo`);
    return "skip";
  }

  if (await wasAlreadyInLemlist(contact.email)) {
    skipped++;
    console.log(`  SKIP: ${contact.email} — already in Lemlist`);
    return "skip";
  }

  // Clean Hunter's occasional merged-name junk (e.g. "Sarah And-Lauren-Murrell" → "Sarah").
  const cleanFirst = normalizeFirstName(contact.firstName);
  if (!cleanFirst) {
    skipped++;
    console.log(`  SKIP: ${contact.email} — unsalvageable firstName "${contact.firstName}"`);
    return "skip";
  }
  contact.firstName = cleanFirst;

  const brandName = domainData.merchant_name || cleanDomain.split(".")[0]
    .replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());
  const desc = domainData.description || "";
  const instagram = (domainData.contact_info || []).find(c => c.type === "instagram");
  const instagramBio = instagram?.description || "";

  const personalizedLine = await generatePersonalizedLine({
    brandName,
    description: desc,
    instagramBio,
    websiteTagline: domainData.title || "",
  });

  const variables = {
    firstName: contact.firstName,
    lastName: contact.lastName,
    companyName: brandName,
    companyDomain: cleanDomain,
    picture: domainData.icon || "",
    linkedinUrl: contact.linkedinUrl || "",
    position: contact.position,
    country: domainData.country_code || "",
    brandDescription: desc.slice(0, 200),
    personalizedLine: personalizedLine || `I came across ${brandName} and really liked what you've built.`,
  };

  console.log(`[${index + 1}] ${cleanDomain} → ${contact.firstName} ${contact.lastName} (${contact.position}) [${contact.source}] → ${contact.email}`);
  if (personalizedLine) console.log(`  line: ${personalizedLine}`);

  const result = await addLeadToLemlist(contact.email, variables);

  if (result.success) {
    pushed++;
    await storeBrand(cleanDomain, domainData);

    let contactId = null;
    const { data: existing } = await supabase.from("contacts")
      .select("id").eq("team_id", TEAM_ID).eq("domain", cleanDomain).single();
    if (existing) {
      contactId = existing.id;
      await supabase.from("contacts").update({
        stage: "Contacted",
        name: `${contact.firstName} ${contact.lastName}`,
        email: contact.email,
      }).eq("id", contactId);
    } else {
      const { data: newContact } = await supabase.from("contacts").insert({
        team_id: TEAM_ID,
        name: `${contact.firstName} ${contact.lastName}`,
        company: brandName,
        domain: cleanDomain,
        email: contact.email,
        stage: "Contacted",
        source: "lemlist",
        country: domainData.country_code || "",
        created_at: new Date().toISOString(),
      }).select().single();
      contactId = newContact?.id;
    }

    // template_variant column is CHARACTER(1) — use "L" for Lemlist.
    const sendInsert = await supabase.from("email_sends").insert({
      team_id: TEAM_ID,
      contact_id: contactId,
      template_variant: "L",
      to_email: contact.email,
      to_name: `${contact.firstName} ${contact.lastName}`,
      subject: `Lemlist campaign ${LEMLIST_CAMPAIGN_ID}`,
      body: `Pushed to Lemlist. Position: ${contact.position}. Source: ${contact.source}. Line: ${personalizedLine || "(fallback)"}`,
      status: "sent",
      resend_id: result.leadId,
      sent_at: new Date().toISOString(),
    });
    if (sendInsert.error) console.log(`  WARN: email_sends insert failed: ${sendInsert.error.message}`);

    console.log(`  PUSHED ✓ (lead: ${result.leadId})`);
  } else {
    failed++;
    console.log(`  FAIL: ${result.error}`);
  }

  await delay(DELAY_MS);
  return result.success ? "pushed" : "failed";
}

// --- Main ---
async function main() {
  console.log("=== Linkable Outreach — StoreLeads → Hunter/Apollo → Lemlist ===");
  console.log(`Campaign: ${LEMLIST_CAMPAIGN_ID}`);
  console.log(`Target this run: ${MAX_LEADS} leads (Lemlist enforces daily send cap)`);
  console.log(`Deadline: ${DEADLINE.toISOString()}\n`);

  let index = 0;
  let batch = 1;

  while (pushed < MAX_LEADS && !pastDeadline()) {
    console.log(`--- StoreLeads batch ${batch} ---`);
    let result;
    try {
      result = await fetchStoreLeadsNext();
    } catch (e) {
      console.log(`StoreLeads error: ${e.message}`);
      break;
    }

    if (result.domains.length === 0) {
      console.log("No more domains."); break;
    }
    console.log(`Got ${result.domains.length} brands`);

    for (const d of result.domains) {
      if (pushed >= MAX_LEADS || pastDeadline()) break;
      await processBrand(d, index);
      index++;
    }

    if (!result.hasMore) {
      console.log("End of StoreLeads list."); break;
    }
    batch++;
  }

  console.log("\n=== COMPLETE ===");
  console.log(`Pushed to Lemlist: ${pushed}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Failed: ${failed}`);
}

main().catch(err => { console.error("Fatal:", err); process.exit(1); });
