steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.discovery-worker
      - -t
      - europe-west2-docker.pkg.dev/linkable-418310/linkable-repo/discovery-worker:v1
      - .
images:
  - europe-west2-docker.pkg.dev/linkable-418310/linkable-repo/discovery-worker:v1
options:
  logging: CLOUD_LOGGING_ONLY
